config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'dashboards#index'

  devise_for :users, :controllers => {
  	:sessions => 'users/sessions'
  }

  resources :users, :except => [:show] do
    collection do
      post  'create_new' => 'users#create'
    end
  end

  resources :dashboards, :only => [:index] do
  	collection do
      get   'products/extractions/channels' => 'products#extractions_channels'
      get   'products'
      get   'staffs' => 'users#staffs'
      get   'channels' => 'channels#reports'
      get   'brands' => 'brands#reports'
    end

    member do
      get   'extractions/stores' => 'products#extractions_stores'
      get   'extractions' => 'products#extractions'

      get   'products/stores' => 'products#stores'
      get   'products/reports' => 'products#reports'
      get   'brand/products' => 'products#brand_reports'

      get   'channels/stores' => 'stores#reports'
    end
  end

  resources :teams, :except => [:show] do
    member do
      get     'accounts'
      post    'add-account-to' => 'teams#add_account_to'
      delete  'remove-account-from' => 'teams#remove_account_from'
    end    
  end

  resources :channels, :except => [:show] do
    member do
      get     'stores'
      post    'add-store-to' => 'channels#add_store_to'
      delete  'remove-store-from' => 'channels#remove_store_from'
    end
  end

  resources :stores, :except => [:show] do
    member do
      get     'products'
      post    'add-product-to' => 'stores#add_product_to'
      delete  'remove-product-from' => 'stores#remove_product_from'
      
      get     'teams'
      post    'add-team-to' => 'stores#add_team_to'
      delete  'remove-team-from' => 'stores#remove_team_from'
    end
  end

  resources :brands, :except => [:show] do
    member do
      get     'products'
      post    'add-product-to' => 'brands#add_product_to'
      delete  'remove-product-from' => 'brands#remove_product_from'
    end
  end

  resources :products, :except => [:show] do
    member do
      post    'upload-report-to' => 'products#upload_report_to'
      post    'report/image/download' => 'products#download_report_image'
      post    'report/date-range' => 'products#date_range'
    end
  end

  resources :reports, :only => [:index] do
    collection do
      post    'generate'
    end

    member do
      get     'products'
    end
  end
end

app/models/store.rb
class Store < ApplicationRecord
	PREFIX = 'STR'

	has_many	:teams,
						:class_name => 'Team',
						:foreign_key => 'store_id',
						:dependent => :nullify

	has_many	:store_product_inventories,
						:class_name => 'StoreProductInventory',
						:foreign_key => 'store_id',
						:dependent => :delete_all

	has_many	:product_reports,
						:class_name => 'ProductReport',
						:foreign_key => 'store_id',
						:dependent => :nullify

	has_many	:products,
						:class_name => 'Product',
						:through => :store_product_inventories

	has_many	:users,
						:class_name => 'User',
						:foreign_key => 'store_id',
						:dependent => :nullify

	belongs_to	:channel,
							:class_name => 'Channel',
							:foreign_key => 'channel_id',
							:required => false

  ApplicationRecord.attach_file(self)

	validates :name, :presence => true
	validates :location, :presence => true

	before_create :generate_id

  scope :unassigned, -> { where(:channel_id => nil) }

  def select_display
  	"#{self.name} - #{self.location}"
  end

  protected

    def generate_id
      generate_base64_id(self)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	before_action { |controller| authenticate_user! unless controller.request.format.json? }
	before_action :stores_list, :only => [:index, :destroy]
	before_action :store_mod, :only => [:edit, :update, :destroy, :products, :add_product_to, :remove_product_from, :teams, :add_team_to, :remove_team_from]
	before_action :associations_list, :only => [:new, :create, :edit, :update]

	def index
		respond_to do |format|
			format.json do
				@stores = Product.find(params[:productcode]).stores.ordered('name', 'ASC') if params[:productcode].present?
				@stores = @stores.where(:channel_id => params[:channelcode]) if params[:channelcode].present?
			end

			format.html
		end
	end

	def reports
		respond_to do |format|
			@channel = Channel.find(params[:id])
			@stores = @channel.stores.ordered('name', 'ASC').paginate(:page => @paramz[:page])
			
			format.html
			format.pdf do
				pdf = ChannelReportPdf.new(@channel, @stores)
				render_pdf(pdf, @channel.name.gsub(' ', '_'))
			end
		end
	end

	def new
		respond_to { |format| format.html{ @store = Store.new } }
	end

	def create
		respond_to do |format|
			format.html do
				@store = Store.new(store_params)
				@store.channel = Channel.find(params[:channel]) if params[:channel].present?

				if @store.save
					flash[:notice] = I18n.t('field_support.record.saved', :record => @store.name, :action => 'created')
					redirect_to stores_path(@paramz)
				else
					flash.now[:alert] = I18n.t('errors.messages.not_saved', :resource => 'store', :count => @store.errors.size)
					render :new
				end
			end
		end
	end

	def edit
		respond_to { |format| format.html }
	end

	def update
		respond_to do |format|
			format.html do
				@store.channel = nil
				@store.channel = Channel.find(params[:channel]) if params[:channel].present?
				
				if @store.update_attributes(store_params)
					flash[:notice] = I18n.t('field_support.record.saved', :record => @store.name, :action => 'updated')
					redirect_to stores_path(@paramz)
				else
					flash.now[:alert] = I18n.t('errors.messages.not_saved', :resource => 'store', :count => @store.errors.size)
					render :edit
				end
			end
		end
	end

	def destroy
		respond_to do |format|
			format.html do
				@store.destroy

				flash[:notice] = I18n.t('field_support.record.saved', :record => @store.name, :action => 'deleted')

				redirect_to stores_path(@paramz)
			end
		end
	end

	def teams
		respond_to do |format|
			format.html do
				@existing_teams = @store.teams
				@available_teams = Team.all - @existing_teams
			end
		end
	end

	def add_team_to
		respond_to do |format|
			format.js do
				team = Team.find(params[:team_id])

				team.store = @store
				team.save

				@existing_teams = @store.teams
				@available_teams = Team.all - @existing_teams
			end
		end
	end

	def remove_team_from
		respond_to do |format|
			format.js do
				team = Team.find(params[:team_id])
				team.store = nil
				team.save

				@existing_teams = @store.teams
				@available_teams = Team.all - @existing_teams
			end
		end
	end

	def products
		respond_to { |format| format.html{ products_list } }
	end

	def add_product_to
		respond_to do |format|
			format.js do
				product = Product.find(params[:product_id])

				spi = StoreProductInventory.new
				spi.inventory_level = params[:level].to_i
				spi.product = product
				spi.store = @store

				spi.save

				products_list
			end
		end
	end

	def remove_product_from
		respond_to do |format|
			format.js do
				spi = StoreProductInventory.find(params[:spi_id])
				spi.destroy

				products_list
			end
		end
	end

	private

		def store_params
			params.require(:store).permit(:name, :location, :avatar)
		end

		def stores_list
			@stores = Store.ordered(params[:sortby], params[:order])
			@stores = @stores.paginate(:page => @paramz[:page])
		end

		def store_mod
			@store = Store.find(params[:id])
		end

		def associations_list
			@channels = Channel.ordered('name', 'ASC')
		end

		def products_list
			@existing_store_product_inventories = @store.store_product_inventories
			@existing_products = @store.products
			@available_products = Product.all - @existing_products
		end
end

app/helpers/stores_helper.rb
module StoresHelper
	def inventory_level_select(id)
		high = StoreProductInventory.inventory_levels[:high]
		medium = StoreProductInventory.inventory_levels[:medium]
		low = StoreProductInventory.inventory_levels[:low]
		out_of_stock = StoreProductInventory.inventory_levels[:out_of_stock]

		inv_level = ''

		inv_level +=	"<select name=\"inventory_level\" class=\"form-control\" id=\"#{id}-level\">"
		inv_level +=		"<option value=\"#{high}\" class=\"bg-green\">High</option>"
		inv_level +=		"<option value=\"#{medium}\" class=\"bg-yellow\">Medium</option>"
		inv_level +=		"<option value=\"#{low}\" class=\"bg-orange\">Low</option>"
		inv_level +=		"<option value=\"#{out_of_stock}\" class=\"bg-red\"}>Out of Stock</option>"
		inv_level += 	"</select>"

		return inv_level.html_safe
	end
end

app/views/stores/add_product_to.js.erb
$('#existing-products').html("<%= escape_javascript(render :partial => 'stores/partials/products/existing_products') %>");
$('#available-products').html("<%= escape_javascript(render :partial => 'stores/partials/products/available_products') %>");

app/views/stores/add_team_to.js.erb
$('#existing-teams').html("<%= escape_javascript(render :partial => 'stores/partials/teams/existing_teams') %>");
$('#available-teams').html("<%= escape_javascript(render :partial => 'stores/partials/teams/available_teams') %>");

app/views/stores/edit.html.erb
<%= form_for(@store, :html => {:class => 'form-horizontal', :id => 'form-stores'}) do |f| %>
	<%= render :partial => 'stores/partials/form_header' %>

	<section class="content">
		<div class="row">
		  <%= render :partial => 'stores/partials/form', :locals => { :f => f } %>
		</div>
	</section>
<% end %>

app/views/stores/index.html.erb
<section class="content-header">
	<h1>
		<%= content_header %>
		<a href="<%= new_store_path(@paramz) %>" class="pull-right btn btn-default"><i class="fa fa-plus"></i> Add Store<a>
	</h1>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<%= field_support_error_alert_notice!(true) %>
			
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Stores List</h3>
				</div>

				<div class="box-body table-responsive">
					<div class="col-md-12" id="list-container">
						<%= render :partial => 'stores/partials/list' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/stores/new.html.erb
<%= form_for(@store, :html => {:class => 'form-horizontal', :id => 'form-stores'}) do |f| %>
	<%= render :partial => 'stores/partials/form_header' %>

	<section class="content">
		<div class="row">
		  <%= render :partial => 'stores/partials/form', :locals => { :f => f } %>
		</div>
	</section>
<% end %>

app/views/stores/products.html.erb
<section class="content-header">
	<h1>
		<%= content_header %>

		<div class="pull-right">
			<a href="<%= stores_path(@paramz) %>" class="btn btn-success">Finish</a>
		</div>
	</h1>
</section>

<section class="content">
	<div class="row">
	  <%= render :partial => 'stores/partials/products/products_form' %>
	</div>
</section>

app/views/stores/remove_product_from.js.erb
$('#existing-products').html("<%= escape_javascript(render :partial => 'stores/partials/products/existing_products') %>");
$('#available-products').html("<%= escape_javascript(render :partial => 'stores/partials/products/available_products') %>");

app/views/stores/remove_team_from.js.erb
$('#existing-teams').html("<%= escape_javascript(render :partial => 'stores/partials/teams/existing_teams') %>");
$('#available-teams').html("<%= escape_javascript(render :partial => 'stores/partials/teams/available_teams') %>");

app/views/stores/reports.html.erb
<section class="content-header">
	<h1>
		<%= content_header %>
		<a href="<%= channels_stores_dashboard_path(params[:id], :format => :pdf) %>" class="pull-right btn btn-danger"><i class="fa fa-file-pdf-o"></i>&nbsp;&nbsp;Generate PDF<a>
	</h1>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">			
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Stores List</h3>
				</div>

				<div class="box-body table-responsive">
					<div class="col-md-12" id="list-container">
						<%= render :partial => 'stores/partials/reports/list' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/stores/teams.html.erb
<section class="content-header">
	<h1>
		<%= content_header %>

		<div class="pull-right">
			<a href="<%= stores_path(@paramz) %>" class="btn btn-success">Finish</a>
		</div>
	</h1>
</section>

<section class="content">
	<div class="row">
	  <%= render :partial => 'stores/partials/teams/teams_form' %>
	</div>
</section>