config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'dashboards#index'

  devise_for :users, :controllers => {
  	:sessions => 'users/sessions'
  }

  resources :users, :except => [:show] do
    collection do
      post  'create_new' => 'users#create'
    end
  end

  resources :dashboards, :only => [:index] do
  	collection do
      get   'products/extractions/channels' => 'products#extractions_channels'
      get   'products'
      get   'staffs' => 'users#staffs'
      get   'channels' => 'channels#reports'
      get   'brands' => 'brands#reports'
    end

    member do
      get   'extractions/stores' => 'products#extractions_stores'
      get   'extractions' => 'products#extractions'

      get   'products/stores' => 'products#stores'
      get   'products/reports' => 'products#reports'
      get   'brand/products' => 'products#brand_reports'

      get   'channels/stores' => 'stores#reports'
    end
  end

  resources :teams, :except => [:show] do
    member do
      get     'accounts'
      post    'add-account-to' => 'teams#add_account_to'
      delete  'remove-account-from' => 'teams#remove_account_from'
    end    
  end

  resources :channels, :except => [:show] do
    member do
      get     'stores'
      post    'add-store-to' => 'channels#add_store_to'
      delete  'remove-store-from' => 'channels#remove_store_from'
    end
  end

  resources :stores, :except => [:show] do
    member do
      get     'products'
      post    'add-product-to' => 'stores#add_product_to'
      delete  'remove-product-from' => 'stores#remove_product_from'
      
      get     'teams'
      post    'add-team-to' => 'stores#add_team_to'
      delete  'remove-team-from' => 'stores#remove_team_from'
    end
  end

  resources :brands, :except => [:show] do
    member do
      get     'products'
      post    'add-product-to' => 'brands#add_product_to'
      delete  'remove-product-from' => 'brands#remove_product_from'
    end
  end

  resources :products, :except => [:show] do
    member do
      post    'upload-report-to' => 'products#upload_report_to'
      post    'report/image/download' => 'products#download_report_image'
      post    'report/date-range' => 'products#date_range'
    end
  end

  resources :reports, :only => [:index] do
    collection do
      post    'generate'
    end

    member do
      get     'products'
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :authenticate_user!
	before_action :product_reports, :only => [:products]

	def index
		respond_to do |format|
			format.html do
				@products = Product.ordered('name', 'ASC')
				@channels = Channel.ordered('name', 'ASC')
			end
		end
	end

	def generate
		respond_to do |format|
			format.pdf do
				product = Product.find(params[:productcode])
				stores = product.stores.ordered('name', 'ASC')
				spis = nil

				if params[:channelcode].present?
					stores = params[:stores].present? && !params[:stores].empty? ? stores.where(:id => params[:stores]) : stores.where(:channel_id => params[:channelcode])
				end

				spis = StoreProductInventory.where(:product => product, :store => stores)
				spis = spis.where(:inventory_level => params[:inventory_levels]) if params[:inventory_levels].present? && !params[:inventory_levels].empty?

				pdf = GeneralReportPdf.new(product, spis)
				render_pdf(pdf, product.name.gsub(' ', '_'))
			end
		end
	end

	def products
		respond_to do |format|
			format.pdf do
				pdf = StaffVisitationsReportPdf.new(@staff, @reports)
				render_pdf(pdf, @staff.name.gsub(' ', '_'))
			end

			format.html
		end
	end

	private

		def product_reports
			@staff = User.find(params[:id])
			@reports = ProductReport.where(:staff => @staff)
		end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<%= form_tag generate_reports_path(:format => :pdf) do %>
	<section class="content-header">
		<h1>
			<%= content_header %>

			<div class="pull-right">
				<button type="submit" class="btn btn-danger"><i class="fa fa-file-pdf-o"></i>&nbsp;&nbsp;Generate PDF</button>
				
			</div>
		</h1>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<%= field_support_error_alert_notice!(true) %>
				
				<div class="box box-primary">
					<div class="box-header with-border">
						<h3 class="box-title">Report Generator</h3>

						<div class="btn-group pull-right" role="group" id="filter-dropdown">
					    <button type="button" class="btn btn-default dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					      Add Filter
					      &nbsp;&nbsp;
					      <span class="caret"></span>
					    </button>

					    <ul class="dropdown-menu">
					      <li id="inventory-level"><a href="#">Inventory Levels</a></li>
					      <li id="channels-and-stores"><a href="#">Channels & Stores</a></li>
					    </ul>
					  </div>
					</div>

					<div class="box-body filters">
						<div class="col-md-4">
							<%= render :partial => 'reports/partials/products' %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
<% end %>

<script>
	inventory_levels_template = "<%= j(render :partial => 'reports/partials/inventory_levels') %>"
	channels_path = "<%= channels_path %>";
	stores_path = "<%= stores_path %>";
</script>

app/views/reports/products.html.erb
<section class="content-header">
	<h1>
		<%= content_header %>

		<div class="pull-right">
			<a href="<%= products_report_path(params[:id], :format => :pdf) %>" class="btn btn-danger"><i class="fa fa-file-pdf-o"></i>&nbsp;&nbsp;Generate PDF</a>
		</div>
	</h1>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">		
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Staff Visitations Reports</h3>
				</div>

				<div class="box-body table-responsive">
					<div class="col-md-12" id="list-container">
						<%= render :partial => 'reports/partials/products_list' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>